
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Work
 */
public class LessonScriptCreator extends javax.swing.JFrame {

    /**
     * Creates new form LessonScriptCreator
     */
    public LessonScriptCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();
        backgroundTextField = new javax.swing.JTextField();
        foregroundLabel = new javax.swing.JLabel();
        foregroundTextField = new javax.swing.JTextField();
        profilePictureLabel = new javax.swing.JLabel();
        profilePictureTextField = new javax.swing.JTextField();
        lessonLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dialogTextArea = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        dialogLabel1 = new javax.swing.JLabel();
        lessonComboBox = new javax.swing.JComboBox();
        speakerLabel = new javax.swing.JLabel();
        speakerTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setText("Lesson Script Creator");

        backgroundLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backgroundLabel.setText("Background:");

        backgroundTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backgroundTextField.setToolTipText("Type the FULL NAME of the background photo.");

        foregroundLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        foregroundLabel.setText("Foreground:");

        foregroundTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        foregroundTextField.setToolTipText("Type the FULL NAME of the foreground photo.");

        profilePictureLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profilePictureLabel.setText("Profile Pict:");

        profilePictureTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profilePictureTextField.setToolTipText("Type the FULL NAME of the profile photo.");

        lessonLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lessonLabel.setText("Lesson:");

        dialogTextArea.setColumns(20);
        dialogTextArea.setLineWrap(true);
        dialogTextArea.setRows(5);
        jScrollPane1.setViewportView(dialogTextArea);

        submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        dialogLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dialogLabel1.setText("Dialog:");

        lessonComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lessonComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lesson 1", "Lesson 2", "Lesson 3", "Lesson 4", "Lesson 5", "Lesson 6", "Lesson 7", "Lesson 8", "Lesson 9", "Lesson 10", "Lesson 11", "Lesson 12", "Lesson 13" }));

        speakerLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        speakerLabel.setText("Speaker:");

        speakerTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        speakerTextField.setToolTipText("Type the FULL NAME of the profile photo.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(title)
                        .addGap(0, 297, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backgroundLabel)
                            .addComponent(foregroundLabel)
                            .addComponent(profilePictureLabel)
                            .addComponent(dialogLabel1)
                            .addComponent(lessonLabel)
                            .addComponent(speakerLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speakerTextField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lessonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(profilePictureTextField)
                            .addComponent(foregroundTextField)
                            .addComponent(backgroundTextField)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(365, 365, 365))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backgroundLabel)
                    .addComponent(backgroundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foregroundLabel)
                    .addComponent(foregroundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profilePictureLabel)
                    .addComponent(profilePictureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speakerLabel)
                    .addComponent(speakerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(submit)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lessonLabel)
                                    .addComponent(lessonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 99, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dialogLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    This method writes all of the input given by the user to a dialog script, and then resets the form.
    */
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        StringBuilder sb = new StringBuilder();
        sb.append(backgroundTextField.getText());
        sb.append("%%");
        sb.append(foregroundTextField.getText());
        sb.append("%%");
        sb.append(profilePictureTextField.getText());
        sb.append("%%");
        sb.append(speakerTextField.getText());
        sb.append("%%");
        sb.append(dialogTextArea.getText());
        sb.append("%%");
        sb.append("0"); //linear?
        sb.append("%%");
        sb.append("0");//reference?
        submitDialog("Lesson"+(lessonComboBox.getSelectedIndex()+1)+ ".txt", sb);
        //backgroundTextField.setText("");
        //foregroundTextField.setText("");
        //profilePictureTextField.setText("");
        dialogTextArea.setText("");
        //speakerTextField.setText("");
    }//GEN-LAST:event_submitActionPerformed

    /*
    This method opens a text file, writes script to it, then closes the text file.
    */
    public static void submitDialog(String location, StringBuilder sb){
        File textFile =new File(location);
        FileWriter out;
        BufferedWriter writeFile;
        try{
            out = new FileWriter(textFile,true);
            writeFile = new BufferedWriter(out);
            writeFile.write(sb.toString());
            writeFile.newLine();
            writeFile.close();
            out.close();
        }
        catch (IOException e){
            System.out.println("problem writing to file");
            System.err.println("IOException :  "+ e.getMessage() );
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LessonScriptCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LessonScriptCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LessonScriptCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LessonScriptCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LessonScriptCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JTextField backgroundTextField;
    private javax.swing.JLabel dialogLabel1;
    private javax.swing.JTextArea dialogTextArea;
    private javax.swing.JLabel foregroundLabel;
    private javax.swing.JTextField foregroundTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox lessonComboBox;
    private javax.swing.JLabel lessonLabel;
    private javax.swing.JLabel profilePictureLabel;
    private javax.swing.JTextField profilePictureTextField;
    private javax.swing.JLabel speakerLabel;
    private javax.swing.JTextField speakerTextField;
    private javax.swing.JButton submit;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
