
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Work
 */
public class TriviaScriptCreator extends javax.swing.JFrame {

    /**
     * Creates new form LessonScriptCreator
     */
    public TriviaScriptCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        lessonLabel = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        answerComboBox = new javax.swing.JComboBox();
        questionLabel = new javax.swing.JLabel();
        questionTextField = new javax.swing.JTextField();
        selection1Label = new javax.swing.JLabel();
        selection2Label = new javax.swing.JLabel();
        selection3Label = new javax.swing.JLabel();
        selection4Label = new javax.swing.JLabel();
        selection1TextField = new javax.swing.JTextField();
        selection2TextField = new javax.swing.JTextField();
        selection3TextField = new javax.swing.JTextField();
        selection4TextField = new javax.swing.JTextField();
        answerLabel = new javax.swing.JLabel();
        lessonComboBox1 = new javax.swing.JComboBox();
        timeSlider = new javax.swing.JSlider();
        timeLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        scoreComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setText("Trivia Script Creator");

        lessonLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lessonLabel.setText("Lesson:");

        submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        answerComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answerComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selection 1", "Selection 2", "Selection 3", "Selection 4" }));

        questionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        questionLabel.setText("Question:");

        questionTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        questionTextField.setToolTipText("Type the FULL NAME of the profile photo.");

        selection1Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selection1Label.setText("Selection 1:");

        selection2Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selection2Label.setText("Selection 2:");

        selection3Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selection3Label.setText("Selection 3:");

        selection4Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selection4Label.setText("Selection 4:");

        selection1TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selection1TextField.setToolTipText("Type the FULL NAME of the profile photo.");

        selection2TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selection2TextField.setToolTipText("Type the FULL NAME of the profile photo.");

        selection3TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selection3TextField.setToolTipText("Type the FULL NAME of the profile photo.");

        selection4TextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        selection4TextField.setToolTipText("Type the FULL NAME of the profile photo.");

        answerLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answerLabel.setText("Answer:");

        lessonComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lessonComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lesson 1", "Lesson 2", "Lesson 3", "Lesson 4", "Lesson 5", "Lesson 6", "Lesson 7", "Lesson 8", "Lesson 9", "Lesson 10", "Lesson 11", "Lesson 12", "Lesson 13" }));

        timeSlider.setMaximum(30);
        timeSlider.setMinimum(9);
        timeSlider.setMinorTickSpacing(3);
        timeSlider.setPaintLabels(true);
        timeSlider.setPaintTicks(true);
        timeSlider.setSnapToTicks(true);
        timeSlider.setValue(9);

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        timeLabel.setText("Time (s):");

        scoreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        scoreLabel.setText("Score:");

        scoreComboBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        scoreComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(title)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(questionLabel)
                                .addGap(27, 27, 27)
                                .addComponent(questionTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selection1Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selection1TextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selection2Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selection2TextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selection3Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selection3TextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selection4Label)
                                    .addComponent(timeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(timeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(selection4TextField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(367, 367, 367)
                                        .addComponent(submit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(lessonLabel)
                                                    .addGap(18, 18, 18))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(answerLabel)
                                                    .addGap(15, 15, 15)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(scoreLabel)
                                                .addGap(29, 29, 29)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(answerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lessonComboBox1, 0, 122, Short.MAX_VALUE)
                                            .addComponent(scoreComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionLabel)
                    .addComponent(questionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selection1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selection1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selection2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selection2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selection3Label)
                    .addComponent(selection3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selection4TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selection4Label))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLabel))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scoreLabel)
                    .addComponent(scoreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerLabel)
                    .addComponent(answerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lessonLabel)
                    .addComponent(lessonComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    This method writes all of the input given by the user to a dialog script, and then resets the form.
    */
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        StringBuilder sb = new StringBuilder();
        sb.append(questionTextField.getText());
        sb.append("%%");
        sb.append(selection1TextField.getText());
        sb.append("$$");
        sb.append(selection2TextField.getText());
        sb.append("$$");
        sb.append(selection3TextField.getText());
        sb.append("$$");
        sb.append(selection4TextField.getText());
        sb.append("%%");
        sb.append(answerComboBox.getSelectedIndex()+1);
        sb.append("%%");
        sb.append(scoreComboBox.getSelectedIndex()+1);
        sb.append("%%");
        sb.append(timeSlider.getValue());
        sb.append("%%");
        submitDialog("Quiz"+(lessonComboBox1.getSelectedIndex()+1)+ ".txt", sb);
        selection1TextField.setText("");
        selection2TextField.setText("");
        selection3TextField.setText("");
        selection4TextField.setText("");
        questionTextField.setText("");
    }//GEN-LAST:event_submitActionPerformed

    /*
    This method opens a text file, writes script to it, then closes the text file.
    */
    public static void submitDialog(String location, StringBuilder sb){
        File textFile =new File(location);
        FileWriter out;
        BufferedWriter writeFile;
        try{
            out = new FileWriter(textFile,true);
            writeFile = new BufferedWriter(out);
            writeFile.write(sb.toString());
            writeFile.newLine();
            writeFile.close();
            out.close();
        }
        catch (IOException e){
            System.out.println("problem writing to file");
            System.err.println("IOException :  "+ e.getMessage() );
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TriviaScriptCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TriviaScriptCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TriviaScriptCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TriviaScriptCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TriviaScriptCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox answerComboBox;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JComboBox lessonComboBox1;
    private javax.swing.JLabel lessonLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JTextField questionTextField;
    private javax.swing.JComboBox scoreComboBox;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel selection1Label;
    private javax.swing.JTextField selection1TextField;
    private javax.swing.JLabel selection2Label;
    private javax.swing.JTextField selection2TextField;
    private javax.swing.JLabel selection3Label;
    private javax.swing.JTextField selection3TextField;
    private javax.swing.JLabel selection4Label;
    private javax.swing.JTextField selection4TextField;
    private javax.swing.JButton submit;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JSlider timeSlider;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
